//CART PRODUCT
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART"
export const BUY_PRODUCT_CART = "BUY_PRODUCT_CART"
export const DECREASE_PRODUCT_CART = "DECREASE_PRODUCT_CART"
export const DELETE_CART = "DELETE_CART"