//AUT LOGINADMIN
//load data LONGINADMIN
export const LOGIN = 'LOGIN'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const SET_IS_LOADING = 'SET_IS_LOADING_AUTH'

//AUT LOGIN_UI
//load data  LOGIN_UI
export const LOGIN_UI = 'LOGIN_UI'
export const LOGIN_UI_FAIL = 'LOGIN_UI_FAIL'
export const LOGIN_UI_SUCCESS = 'LOGIN_UI_SUCCESS'
export const LOGOUT_UI = 'LOGOUT_UI'
export const GET_PROFILE_UI = 'GET_PROFILE_UI'
export const GET_PROFILE_UI_FAIL = 'GET_PROFILE_UI_FAIL'
export const GET_PROFILE_UI_SUCCESS = 'GET_PROFILE_UI_SUCCESS'
export const SET_IS_LOADING_UI = 'SET_IS_LOADING_UI'


//DATA USER ADMIN
//load data usersAdmin
export const LOAD_USERS_ADMIN_START = "LOAD_USERS_ADMIN_START"
export const LOAD_USERS_ADMIN_SUCCESS = "LOAD_USERS_ADMIN_SUCCESS"
export const LOAD_USERS_ADMIN_ERROR = "LOAD_USERS_ADMIN_ERROR"
//create usersAdmin
export const CREATE_USER_ADMIN_START = "CREATE_USER_ADMIN_START"
export const CREATE_USER_ADMIN_SUCCESS = "CREATE_USER_ADMIN_SUCCESS"
export const CREATE_USER_ADMIN_ERROR = "CREATE_USER_ADMIN_ERROR"
//delete usersAdmin
export const DELETE_USER_ADMIN_START = "DELETE_USER_ADMIN_START"
export const DELETE_USER_ADMIN_SUCCESS = "DELETE_USER_ADMIN_SUCCESS"
export const DELETE_USER_ADMIN_ERROR = "DELETE_USER_ADMIN_ERROR"
//update usersAdmin
export const UPDATE_USER_ADMIN_START = "UPDATE_USER_ADMIN_START"
export const UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS"
export const UPDATE_USER_ADMIN_ERROR = "UPDATE_USER_ADMIN_ERROR"

//DATA CATEGORY
//load data CATEGORY
export const LOAD_CATEGORY_START = "LOAD_CATEGORY_START"
export const LOAD_CATEGORY_SUCCESS = "LOAD_CATEGORY_SUCCESS"
export const LOAD_CATEGORY_ERROR = "LOAD_CATEGORY_ERROR"
//create CATEGORY
export const CREATE_CATEGORY_START = "CREATE_CATEGORY_START"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR"
//delete CATEGORY
export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START"
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR"
//update CATEGORY
export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START"
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR"

//DATA PRODUCT
//load data PRODUCT
export const LOAD_PRODUCT_START = "LOAD_PRODUCT_START"
export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS"
export const LOAD_PRODUCT_ERROR = "LOAD_PRODUCT_ERROR"
//create PRODUCT
export const CREATE_PRODUCT_START = "CREATE_PRODUCT_START"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR"
//delete PRODUCT
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"
//update PRODUCT
export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"

//DATA BANNER
//load data BANNER
export const LOAD_BANNER_START = "LOAD_BANNER_START"
export const LOAD_BANNER_SUCCESS = "LOAD_BANNER_SUCCESS"
export const LOAD_BANNER_ERROR = "LOAD_BANNER_ERROR"
//create BANNER
export const CREATE_BANNER_START = "CREATE_BANNER_START"
export const CREATE_BANNER_SUCCESS = "CREATE_BANNER_SUCCESS"
export const CREATE_BANNER_ERROR = "CREATE_BANNER_ERROR"
//delete BANNER
export const DELETE_BANNER_START = "DELETE_BANNER_START"
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS"
export const DELETE_BANNER_ERROR = "DELETE_BANNER_ERROR"
//update BANNER
export const UPDATE_BANNER_START = "UPDATE_BANNER_START"
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS"
export const UPDATE_BANNER_ERROR = "UPDATE_BANNER_ERROR"

//load data usersUI
export const LOAD_USERS_START = "LOAD_USERS_START"
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS"
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR"
//create USERUI
export const CREATE_USERUI_START = "CREATE_USERUI_START"
export const CREATE_USERUI_SUCCESS = "CREATE_USERUI_SUCCESS"
export const CREATE_USERUI_ERROR = "CREATE_USERUI_ERROR"
//delete USERUI
export const DELETE_USERUI_START = "DELETE_USERUI_START"
export const DELETE_USERUI_SUCCESS = "DELETE_USERUI_SUCCESS"
export const DELETE_USERUI_ERROR = "DELETE_USERUI_ERROR"
//update USERUI
export const UPDATE_USERUI_START = "UPDATE_USERUI_START"
export const UPDATE_USERUI_SUCCESS = "UPDATE_USERUI_SUCCESS"
export const UPDATE_USERUI_ERROR = "UPDATE_USERUI_ERROR"


//DATA SLIDER
//load data SLIDER
export const LOAD_SLIDER_START = "LOAD_SLIDER_START"
export const LOAD_SLIDER_SUCCESS = "LOAD_SLIDER_SUCCESS"
export const LOAD_SLIDER_ERROR = "LOAD_SLIDER_ERROR"
//create SLIDER
export const CREATE_SLIDER_START = "CREATE_SLIDER_START"
export const CREATE_SLIDER_SUCCESS = "CREATE_SLIDER_SUCCESS"
export const CREATE_SLIDER_ERROR = "CREATE_SLIDER_ERROR"
//delete SLIDER
export const DELETE_SLIDER_START = "DELETE_SLIDER_START"
export const DELETE_SLIDER_SUCCESS = "DELETE_SLIDER_SUCCESS"
export const DELETE_SLIDER_ERROR = "DELETE_SLIDER_ERROR"
//update SLIDER
export const UPDATE_SLIDER_START = "UPDATE_SLIDER_START"
export const UPDATE_SLIDER_SUCCESS = "UPDATE_SLIDER_SUCCESS"
export const UPDATE_SLIDER_ERROR = "UPDATE_SLIDER_ERROR"


//DATA ORDER
//load data ORDER
export const LOAD_ORDER_START = "LOAD_ORDER_START"
export const LOAD_ORDER_SUCCESS = "LOAD_ORDER_SUCCESS"
export const LOAD_ORDER_ERROR = "LOAD_ORDER_ERROR"
//create ORDER
export const CREATE_ORDER_START = "CREATE_ORDER_START"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR"
//delete ORDER
export const DELETE_ORDER_START = "DELETE_ORDER_START"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR"
//update ORDER
export const UPDATE_ORDER_START = "UPDATE_ORDER_START"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR"

//DATA COMMENT
//load data COMMENT
export const LOAD_COMMENT_START = "LOAD_COMMENT_START"
export const LOAD_COMMENT_SUCCESS = "LOAD_COMMENT_SUCCESS"
export const LOAD_COMMENT_ERROR = "LOAD_COMMENT_ERROR"
//create COMMENT
export const CREATE_COMMENT_START = "CREATE_COMMENT_START"
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR"
//delete COMMENT
export const DELETE_COMMENT_START = "DELETE_COMMENT_START"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR"
